### ISSUE TITLE
Cannot run as docker

### ISSUE THREAD

**Issue by ycc3000** [artela-network/artela#100]
dear,
I run as docker-compose, it start up, but will stop unexpected.  artelad command in docker container also does not work.

**Comment by luketheart** [comment]
Hi @ycc3000, can you please show me what error occurred, the output of docker logs and the output related to artelad startup??

**Comment by ycc3000** [comment]
dear @luketheart ,
please see image below.
when I exec into container and run ./artelad status or other commands, always get 'connection confused'

![Weixin Image_20240401102150](https://github.com/artela-network/artela/assets/22928461/1ba07c2f-a39c-4ef7-bef2-d8e511088046)

**Comment by luketheart** [comment]
Sorry for the late reply. It seems that your db has a data problem, which may be caused by not having the correct rollback. You can try using `artelad rollback --hard` to rollback last height again. If this node is a validator, you also need to modify the wrong state data in ~/.artelad/data/priv_validator_state.json.
If this still doesn't solve your problem, I recommend resetting your data and then starting your node from the latest snapshot according to https://docs.artela.network/develop/node/run-full-node.

**Comment by ycc3000** [comment]
dear @luketheart ,
thank you for your response, I tried to create new environment and successfully.
there's some hard code, eg: chain-id is artela_11820-1, not chain-id artela_11822-1, I have to use _testnet/node[0-3] for volume, change it will be failure, etc.

**Comment by luketheart** [comment]
Got it, thank you for your feedback, we will make some fixes.
